# permissions for end users to edit argorollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: argorollouts-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: argo-rollouts-operator
    app.kubernetes.io/part-of: argo-rollouts-operator
    app.kubernetes.io/managed-by: kustomize
  name: argorollouts-editor-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - argorollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - argorollouts/status
  verbs:
  - get
