name: Run E2E tests
on:
  push:
    branches:
      - 'master'
      - 'release-*'
  pull_request:
    branches:
      - '*'

jobs:

  test-e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k3s-version: [ v1.28.2 ]
        # k3s-version: [ v1.28.2, v1.27.6, v1.26.9 ]
    steps:
      - name: Install K3D
        run: |
          set -x
          curl -sfL https://get.k3s.io | sh -
          sudo chmod -R a+rw /etc/rancher/k3s
          sudo mkdir -p $HOME/.kube && sudo chown -R runner $HOME/.kube
          sudo k3s kubectl config view --raw > $HOME/.kube/config
          sudo chown runner $HOME/.kube/config
          sudo chmod go-r $HOME/.kube/config
          kubectl version
          k3d version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: GH actions workaround - Kill XSP4 process
        run: |
          sudo pkill mono || true
      - name: Add /usr/local/bin to PATH
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH
      - name: Download Go dependencies
        run: |
          go mod download
      - name: Run the operator locally
        run: |
          set -o pipefail
          make install generate fmt vet
          go run ./main.go 2>&1 | tee /tmp/e2e-operator-run.log &
      - name: Run tests
        run: |
          set -o pipefail
          bash make test-e2e 2>&1 | tee /tmp/e2e-test.log
