# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    branches:
      - '*'     

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v5.0.0
      with:
        go-version-file: './go.mod'

    - name: Build
      run: make build

    - name: Test
      run: make test

  gofmt:
    name: "Ensure that code is gofmt-ed"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Golang
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: './go.mod'
      - name: "Run make fmt and then 'git diff' to see if anything changed: to fix this check, run make fmt and then commit the changes."
        run: |
          make fmt
          git diff --exit-code -- .
  