name: Lint code
on:

  push:
    branches:
      - 'main'
      - 'release-*'

  pull_request:
    branches:
      - '*'     

jobs:
  lint_code:
    name: Run golangci-lint and gosec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "run gosec"
        run: |
          cd $GITHUB_WORKSPACE
          make gosec
      - name: "run golangci-lint"
        run: |
          cd $GITHUB_WORKSPACE
          make lint
